### ISSUE TITLE
status.shouldCollectConsent is FALSE after publishing a new version of a config

### ISSUE THREAD

**Issue by VitaSokolova** [Usercentrics/android-sample#13]
Hi! I didn't find a repository with mobile SDK, please redirect me there, if this issue belongs to another project. 

Recently I've added a new service into my app's config and published the changes. The consent collection has not been triggered by usercentrics. `shouldCollectConsent ` return false despite new version of a config has been published and I see the new service as "disable" on production, when I open consent settings. I expected the opposite behaviour, as it described in the [documentation](https://usercentrics.com/docs/apps/api/core-api/#usercentricsreadystatus). 

![Screenshot 2023-12-05 at 11 32 56](https://github.com/Usercentrics/android-sample/assets/14140643/bb1287ee-d5f3-4448-959e-a738b796cc85)

**Comment by uc-piotukh** [comment]
Good morning @VitaSokolova!
Could you please raise a ticket through with our support, including the configuration ID you are using for this and which SDK version you are using.
https://usercentricssupport.zendesk.com/hc/en-us/requests/new 

Thanks a lot!

Kind regards,
Aliaksandra
Usercentrics
Tech Support Team

**Comment by VitaSokolova** [comment]
Done ✅
