### ISSUE TITLE
Consent dialog buttons are not visible when System Font size is large

### ISSUE THREAD

**Issue by aercanozcan** [Usercentrics/android-sample#4]
**Steps to reproduce**:

1. Increase the system Font size from settings to largest
2. display the consent dialog
**Result**:
It looks like the text content is wrapped in a scrollable container but buttons are not therefore users with larger font sizes gets stuck with the dialog.

<img width="288" alt="Screenshot 2022-03-17 at 11 37 24" src="https://user-images.githubusercontent.com/2137007/158791563-ce14478e-0d4e-4f19-963c-44124c4114fe.png">

<img width="288" alt="Screenshot 2022-03-17 at 10 58 49" src="https://user-images.githubusercontent.com/2137007/158791585-ce490cac-dd53-42ae-994d-41667389ae0e.png">

**Comment by userCTest** [comment]
Hi @aercanozcan,

we have tried to replicate the issue, but using this sample app and others we have available, we seem unable to. Using the largest font, we get the buttons quite functional and visible:
![image](https://user-images.githubusercontent.com/67687938/158805607-4bafc353-8925-45e3-aa36-60d33f6dfac2.png)
Could you please provide us more details? 
If you could please open a ticket for technical support [here](https://usercentrics.com/support/), including all details like SDK version used, settingsId, etc, we would be glad to assist you.

With kind regards,
Rui Reis
Usercentrics
Tech Support Team

**Comment by aercanozcan** [comment]
Hi, This bug happens to the users who have smaller screens. The bug is reproducible in on Galaxy Nexus devices which you can emulate(screen shot taken from emulator)

**Comment by daneelOlivaw76** [comment]
Hey Ercan,

tested with 2.1.0 on a Galaxy Nexus and all seems well
![Screen Shot 2022-03-17 at 13 36 45](https://user-images.githubusercontent.com/38663114/158820579-50cc0ec4-5692-452d-8e93-5a99c428a5bb.png)
Anyway, can you maybe try with the latest version of the SDK and see if the issue persists? Also, it could be something related to your specific settingsID, and in that case a [support](https://usercentrics.com/support/) ticket would be a better vehicle of discussion than this thread here.

Best,
Rui

**Comment by aercanozcan** [comment]
Bug is not reproducible with version 2.2.0. thank you.

**Comment by userCTest** [comment]
Great news, glad it's solved.
If you need any further assistance or just have a query, just let us know. ;)
