### ISSUE TITLE
Support custom letter spacing in BannerSettings

### ISSUE THREAD

**Issue by smuldr** [Usercentrics/android-sample#7]
Our app uses Usercentrics SDK version 2.7.5 to help manage the consents. We use the BannerSettings to programmatically customize the style of our banners and add support for dark mode. It works pretty well but we would like to have a little bit more options to make it look perfect.

Specifically: our button text style has a [custom letter spacing](https://developer.android.com/reference/android/widget/TextView#setLetterSpacing(float)) to help increase the readability of our custom font. Could this be added to the `BannerFont` and `ButtonSettings` APIs?

**Comment by userCTest** [comment]
Hey @smuldr ,

thanks a lot for your feedback, we appreciate it!
Could we please ask you to open a feature request [here](https://usercentrics.atlassian.net/servicedesk/customer/portal/2) with the details of your use case?

Thanks in advance!
Rui
